const fa=n=>Number(n||0).toLocaleString('fa-IR');
let current=new URLSearchParams(location.search).get('cat')||'';
const apiUrl=()=>window.APP_CONFIG?.API_URL||'';
function menu(){document.getElementById('drawer')?.classList.toggle('open');document.getElementById('shade')?.classList.toggle('show')}
function closeMenu(){document.getElementById('drawer')?.classList.remove('open');document.getElementById('shade')?.classList.remove('show')}
function logout(){localStorage.removeItem('vplus_user');localStorage.removeItem('vplus_token');alert('از حساب خارج شدید');location.href='index.html'}
function img(p){return p.i?`<img src="image/${p.i}" alt="${p.n}" onerror="this.outerHTML='<span class=\"fallback\">${p.e}</span>'">`:`<span class="fallback">${p.e}</span>`}
function card(p){return `<article class="product"><a href="product.html?id=${p.id}"><div class="pic">${img(p)}</div><div class="info"><span class="brand">${p.b}</span><h3>${p.n}</h3><div class="bottom"><span class="price">${fa(p.p)} <small>تومان</small></span><button class="add" onclick="event.preventDefault();add(${p.id})">+</button></div></div></a></article>`}
function cat(c){current=c;render()}
function render(){let q=(document.getElementById('search')?.value||'').trim().toLowerCase();let a=PRODUCTS.filter(p=>(!current||current==='all'||p.c===current)&&(!q||(p.n+p.b).toLowerCase().includes(q)));const g=document.getElementById('grid');if(g)g.innerHTML=a.map(card).join('')||'<div class="card">محصولی پیدا نشد.</div>';const r=document.getElementById('result');if(r)r.textContent=fa(a.length)+' محصول';document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x.dataset.cat===current))}
function get(){try{return JSON.parse(localStorage.getItem('vplus_cart')||'[]')}catch{return []}}
function save(c){localStorage.setItem('vplus_cart',JSON.stringify(c));count()}
function count(){let n=get().reduce((s,x)=>s+Number(x.q||0),0);document.querySelectorAll('#count').forEach(e=>e.textContent=fa(n))}
function add(id){let c=get(),x=c.find(y=>y.id==id);x?x.q++:c.push({id,q:1});save(c);toast('قطعه به سبد خرید اضافه شد ✓')}
function removeItem(id){save(get().filter(x=>x.id!=id));renderCart()}
function changeQty(id,d){let c=get(),x=c.find(y=>y.id==id);if(!x)return;x.q+=d;if(x.q<1)c=c.filter(y=>y.id!=id);save(c);renderCart()}
function toast(t){let e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function renderDetail(){let e=document.getElementById('detail');if(!e)return;let p=PRODUCTS.find(x=>x.id==+(new URLSearchParams(location.search).get('id')||1))||PRODUCTS[0];e.innerHTML=`<div class="detail"><div class="detailpic">${img(p)}</div><div><span class="brand">${p.b}</span><h1>${p.n}</h1><p>قطعه با کیفیت مناسب خودروهای سازگار.</p><h2>${fa(p.p)} تومان</h2><button class="gold" onclick="add(${p.id})">افزودن به سبد خرید</button></div></div>`}
function renderCart(){let e=document.getElementById('cart');if(!e)return;let c=get();if(!c.length){e.innerHTML='<div class="card">سبد خرید خالی است<br><a class="gold-link" href="index.html">← فروشگاه</a></div>';return}let total=0;e.innerHTML=c.map(x=>{let p=PRODUCTS.find(y=>y.id==x.id);if(!p)return '';total+=p.p*x.q;return `<div class="cartrow"><span class="mini">${p.e}</span><div><b>${p.n}</b><small>${p.b}</small></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${fa(x.q)}</b><button onclick="changeQty(${p.id},1)">+</button></div><b>${fa(p.p*x.q)} تومان</b><button class="remove" onclick="removeItem(${p.id})">حذف</button></div>`}).join('')+`<div class="total"><b>مبلغ نهایی: ${fa(total)} تومان</b><button class="gold" onclick="submitOrder()">ثبت سفارش</button></div>`}
async function submitOrder(){const c=get();if(!c.length)return toast('سبد خرید خالی است');const user=getUser();if(!user){location.href='account.html?return=cart';return}if(!apiReady())return toast('ابتدا آدرس Apps Script را در js/config.js وارد کنید');try{await api('createOrder',{customerId:user.id||user.phone,customerName:user.name||'',phone:user.phone||'',items:c.map(x=>{let p=PRODUCTS.find(y=>y.id==x.id);return {id:p.id,name:p.n,brand:p.b,qty:x.q,price:p.p}})});save([]);renderCart();alert('سفارش با موفقیت ثبت شد ✓');location.href='orders.html'}catch(e){alert(e.message||'ثبت سفارش انجام نشد')}}
function getUser(){try{return JSON.parse(localStorage.getItem('vplus_user')||'null')}catch{return null}}
function apiReady(){return apiUrl()&&!apiUrl().includes('PASTE_YOUR')}
async function api(action,data={}){if(!apiReady())throw Error('API تنظیم نشده است.');const r=await fetch(apiUrl(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...data})});const j=await r.json();if(!j.ok)throw Error(j.message||'خطای سرور');return j}
async function login(){const phone=document.getElementById('phone')?.value.trim(),name=document.getElementById('name')?.value.trim()||'کاربر';if(!phone)return toast('شماره موبایل را وارد کنید');if(!apiReady()){localStorage.setItem('vplus_user',JSON.stringify({id:phone,phone,name}));location.href='index.html';return}try{const r=await api('login',{phone,name});localStorage.setItem('vplus_user',JSON.stringify(r.user));toast('ورود موفق بود');setTimeout(()=>location.href='index.html',500)}catch(e){toast(e.message)}}
async function loadOrders(){const e=document.getElementById('orders');if(!e)return;const u=getUser();if(!u){e.innerHTML='<div class="card">برای دیدن سفارش‌ها ابتدا وارد حساب شوید.<br><a class="gold-link" href="account.html">ورود</a></div>';return}if(!apiReady()){e.innerHTML='<div class="card">API تنظیم نشده است.</div>';return}try{const r=await api('orders',{customerId:u.id||u.phone,phone:u.phone});e.innerHTML=r.orders?.length?r.orders.map(o=>`<div class="order"><b>سفارش ${o.id}</b><span>${o.status||'در انتظار'}</span><small>${o.total?fa(o.total)+' تومان':''}</small></div>`).join(''):'<div class="card">هنوز سفارشی ثبت نشده است.</div>'}catch(e){document.getElementById('orders').innerHTML='<div class="card">خطا در دریافت سفارش‌ها.</div>'}}
async function sendSupport(){const u=getUser();const message=document.querySelector('textarea')?.value.trim();if(!message)return toast('پیام را وارد کنید');const phone=u?.phone||prompt('شماره موبایل را وارد کنید:');if(!phone)return;if(!apiReady()){return toast('API تنظیم نشده است.')}try{await api('support',{phone,name:u?.name||'',message});document.querySelector('textarea').value='';toast('پیام شما ثبت شد ✓')}catch(e){toast(e.message)}}
function prices(){let e=document.getElementById('prices');if(e)e.innerHTML=PRODUCTS.map(p=>`<tr><td>${p.n}</td><td>${p.b}</td><td>${fa(p.p)} تومان</td></tr>`).join('')}
function renderAccount(){const u=getUser(),box=document.getElementById('accountBox');if(!box)return;box.innerHTML=u?`<div class="avatar">♙</div><h1>حساب کاربری</h1><p>${u.name||'کاربر'}</p><p>${u.phone||''}</p><button class="gold" onclick="logout()">خروج از حساب</button>`:`<div class="avatar">♙</div><h1>ورود / ثبت‌نام</h1><input id="name" placeholder="نام و نام خانوادگی"><input id="phone" inputmode="tel" placeholder="شماره موبایل"><button class="gold" onclick="login()">ورود</button>`}
function categories(){const e=document.getElementById('categoryList');if(e)e.innerHTML=CATEGORIES.map(c=>`<a class="category" href="products.html?cat=${c[0]}"><span>${c[2]}</span><b>${c[1]}</b><span>‹</span></a>`).join('')}
function toggleCategories(){document.getElementById('categories')?.classList.toggle('show')}
function updateMenu(){const e=document.getElementById('drawer');if(!e)return;const u=getUser();e.querySelector('[data-user]')?.classList.toggle('hidden',!u)}
document.addEventListener('DOMContentLoaded',()=>{count();render();renderDetail();renderCart();prices();renderAccount();loadOrders();categories();updateMenu();document.getElementById('search')?.addEventListener('input',render)});
