const PRODUCTS=[
{id:1,name:'لنت ترمز جلو پژو ۴۰۵',brand:'ایساکو',cat:'brake',price:850000,icon:'🛞',popular:98,desc:'لنت ترمز جلو باکیفیت مناسب پژو ۴۰۵، پارس و سمند. عملکرد مطمئن و عمر مفید بالا.',spec:{برند:'ایساکو',کد_فنی:'BP-405-F',مناسب:'پژو ۴۰۵ / پارس / سمند',وضعیت:'موجود'}},
{id:2,name:'فیلتر روغن پژو TU5',brand:'عظام',cat:'consumable',price:245000,icon:'🧰',popular:95,desc:'فیلتر روغن استاندارد برای موتورهای TU5 با فیلتراسیون مناسب و کیفیت ساخت بالا.',spec:{برند:'عظام',کد_فنی:'OF-TU5-01',مناسب:'پژو ۲۰۶ / ۲۰۷ / رانا',وضعیت:'موجود'}},
{id:3,name:'شمع موتور پایه کوتاه',brand:'NGK',cat:'engine',price:390000,icon:'🔩',popular:93,desc:'شمع موتور NGK مناسب انواع خودروهای منتخب با جرقه پایدار و طول عمر بالا.',spec:{برند:'NGK',کد_فنی:'BKR6E',مناسب:'خودروهای سازگار با BKR6E',وضعیت:'موجود'}},
{id:4,name:'دیسک و صفحه کلاچ',brand:'عظام',cat:'engine',price:4250000,icon:'⚙️',popular:91,desc:'مجموعه دیسک و صفحه کلاچ با کیفیت مناسب استفاده روزمره و شهری.',spec:{برند:'عظام',کد_فنی:'CL-206',مناسب:'پژو ۲۰۶ تیپ ۲',وضعیت:'موجود'}},
{id:5,name:'کمک فنر جلو',brand:'ایساکو',cat:'suspension',price:1780000,icon:'🔧',popular:88,desc:'کمک فنر جلو با کیفیت ساخت بالا برای سواری نرم‌تر و کنترل بهتر خودرو.',spec:{برند:'ایساکو',کد_فنی:'SH-405-F',مناسب:'پژو ۴۰۵ / پارس',وضعیت:'موجود'}},
{id:6,name:'دینام خودرو',brand:'ایساکو',cat:'electric',price:6800000,icon:'🔋',popular:86,desc:'دینام خودرو با عملکرد پایدار برای تامین برق سیستم‌های خودرو.',spec:{برند:'ایساکو',کد_فنی:'ALT-90A',مناسب:'خودروهای منتخب ایران خودرو',وضعیت:'موجود'}},
{id:7,name:'آینه بغل راست',brand:'عظام',cat:'body',price:1150000,icon:'🚘',popular:80,desc:'آینه جانبی با کیفیت مناسب تعویض و نصب آسان.',spec:{برند:'عظام',کد_فنی:'MIR-R',مناسب:'پژو ۲۰۶',وضعیت:'موجود'}},
{id:8,name:'فیلتر هوا',brand:'ایساکو',cat:'consumable',price:195000,icon:'🧹',popular:84,desc:'فیلتر هوای استاندارد برای جلوگیری از ورود گردوغبار به موتور.',spec:{برند:'ایساکو',کد_فنی:'AF-405',مناسب:'پژو ۴۰۵ / پارس',وضعیت:'موجود'}},
{id:9,name:'لنت ترمز عقب پراید',brand:'عظام',cat:'brake',price:620000,icon:'🛞',popular:82,desc:'لنت ترمز عقب مناسب پراید با کیفیت و دوام مطلوب.',spec:{برند:'عظام',کد_فنی:'BP-PD-R',مناسب:'پراید',وضعیت:'موجود'}},
{id:10,name:'واتر پمپ',brand:'ایساکو',cat:'engine',price:1280000,icon:'💧',popular:79,desc:'واتر پمپ با کیفیت برای گردش مناسب مایع خنک‌کننده موتور.',spec:{برند:'ایساکو',کد_فنی:'WP-TU5',مناسب:'TU5',وضعیت:'موجود'}},
{id:11,name:'بلبرینگ چرخ جلو',brand:'عظام',cat:'suspension',price:890000,icon:'⚙️',popular:77,desc:'بلبرینگ چرخ با عملکرد روان و مقاومت مناسب.',spec:{برند:'عظام',کد_فنی:'WB-F01',مناسب:'خودروهای منتخب',وضعیت:'موجود'}},
{id:12,name:'چراغ جلو راست',brand:'ایساکو',cat:'body',price:2350000,icon:'💡',popular:74,desc:'چراغ جلو با طراحی استاندارد و نصب آسان.',spec:{برند:'ایساکو',کد_فنی:'HL-R01',مناسب:'پژو ۴۰۵',وضعیت:'موجود'}}];

function card(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-img">${p.icon}<span class="badge">موجود</span></div><div class="product-info"><span class="product-brand">${p.brand}</span><h3>${p.name}</h3></div></a><div class="product-info" style="padding-top:0"><div class="price"><div><strong>${fa(p.price)}</strong><small> تومان</small></div><button class="add" onclick="addToCart(${p.id})">+</button></div></div></article>`}

function renderFeatured(){const el=document.getElementById('featuredProducts');if(el)el.innerHTML=PRODUCTS.slice().sort((a,b)=>b.popular-a.popular).slice(0,4).map(card).join('')}
function applyFilters(){const q=(document.getElementById('shopSearch')?.value||'').trim().toLowerCase(),cat=document.getElementById('catFilter')?.value||'',brand=document.getElementById('brandFilter')?.value||'',sort=document.getElementById('sortFilter')?.value||'popular';let arr=PRODUCTS.filter(p=>(!q||(p.name+' '+p.brand+' '+JSON.stringify(p.spec)).toLowerCase().includes(q))&&(!cat||p.cat===cat)&&(!brand||p.brand===brand));arr.sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:b.popular-a.popular);const g=document.getElementById('productGrid');if(g)g.innerHTML=arr.map(card).join('');const empty=document.getElementById('empty');if(empty)empty.hidden=arr.length>0;const txt=document.getElementById('resultText');if(txt)txt.textContent=fa(arr.length)+' محصول پیدا شد'}
function resetFilters(){['shopSearch','catFilter','brandFilter'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});if(document.getElementById('sortFilter'))document.getElementById('sortFilter').value='popular';applyFilters()}
function renderDetail(){const el=document.getElementById('productDetail');if(!el)return;const id=Number(new URLSearchParams(location.search).get('id'))||1,p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];el.innerHTML=`<div class="detail"><div class="detail-img">${p.icon}</div><div><span class="eyebrow">${p.brand}</span><h1>${p.name}</h1><p class="desc">${p.desc}</p><div class="specs">${Object.entries(p.spec).map(([k,v])=>`<div><span>${k.replace('_',' ')}</span><b>${v}</b></div>`).join('')}</div><div class="price"><div><strong>${fa(p.price)}</strong><small> تومان</small></div><span>✓ ضمانت اصالت</span></div><div class="buy-row"><div class="qty"><button onclick="changeDetailQty(-1)">−</button><span id="detailQty">۱</span><button onclick="changeDetailQty(1)">+</button></div><button class="primary" style="height:45px;flex:1" onclick="addDetail()">افزودن به سبد خرید</button></div></div></div>`;window.detailProduct=p}
let detailQty=1;function changeDetailQty(n){detailQty=Math.max(1,detailQty+n);const e=document.getElementById('detailQty');if(e)e.textContent=fa(detailQty)}function addDetail(){for(let i=0;i<detailQty;i++)addToCart(window.detailProduct.id);toast('محصول به سبد خرید اضافه شد ✓')}
function renderCart(){const el=document.getElementById('cartPage');if(!el)return;const c=getCart();if(!c.length){el.innerHTML='<div class="empty">سبد خرید شما خالی است.<br><a class="more" href="products.html">رفتن به فروشگاه ←</a></div>';return}let total=0;const rows=c.map(x=>{const p=PRODUCTS.find(y=>y.id===x.id);if(!p)return '';total+=p.price*x.qty;return `<div class="cart-item"><div class="mini-img">${p.icon}</div><div><h3>${p.name}</h3><small>${p.brand} · ${fa(p.price)} تومان</small></div><div class="qty"><button onclick="changeCart(${p.id},-1)">−</button><span>${fa(x.qty)}</span><button onclick="changeCart(${p.id},1)">+</button></div><button class="remove" onclick="removeCart(${p.id})">حذف</button></div>`}).join('');el.innerHTML=`<div class="cart-layout"><div class="cart-list">${rows}</div><aside class="summary"><h3>خلاصه سفارش</h3><div class="sumline"><span>جمع کالاها</span><b>${fa(total)} تومان</b></div><div class="sumline"><span>هزینه ارسال</span><b>رایگان</b></div><div class="sumline total"><span>مبلغ نهایی</span><b>${fa(total)} تومان</b></div><button class="primary full" onclick="alert('این نسخه نمایشی است؛ درگاه پرداخت بعداً متصل می‌شود.')">ادامه و ثبت سفارش</button></aside></div>`}
function changeCart(id,n){const c=getCart(),x=c.find(y=>y.id===id);if(x){x.qty+=n;if(x.qty<1)c.splice(c.indexOf(x),1)}saveCart(c);renderCart()}function removeCart(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}
document.addEventListener('DOMContentLoaded',()=>{renderFeatured();renderDetail();renderCart();if(document.getElementById('productGrid')){const p=new URLSearchParams(location.search);if(p.get('q'))document.getElementById('shopSearch').value=p.get('q');if(p.get('cat'))document.getElementById('catFilter').value=p.get('cat');applyFilters()}const brand=document.getElementById('brand');if(brand)brand.addEventListener('change',()=>{const m=document.getElementById('model');const data={'ایران خودرو':['پژو ۴۰۵','پژو ۲۰۶','پژو ۲۰۷','سمند','دنا'],'سایپا':['پراید','تیبا','شاهین'],'کرمان موتور':['جک J4','جک S5'],'مدیران خودرو':['X22','X55'],'تویوتا':['کرولا','کمری'],'هیوندای':['النترا','سوناتا'],'کیا':['سراتو','اسپورتیج']};m.innerHTML=(data[brand.value]||['مدل خودرو']).map(x=>`<option>${x}</option>`).join('')})});